### ISSUE TITLE
difference gcc vs intel compilation

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [bwa-mem2/bwa-mem2#72]
I was just wondering how much of a performance difference there is between these compilers? Which order of magnitude (1%, 10%, 100%) slower?

I am currently working to put bwa-mem2 on [bioconda](https://bioconda.github.io/) and as (this) package manager very much prefers to compile the package itself I am wondering how much of a performance hit we should expect, and whether or not to use the precompiled binaries.

**Comment by sanchit-misra** [comment]
I see on an average about 5-10% difference.

**Comment by Maarten-vd-Sande** [comment]
Thanks for coming back to this :)

just FYI, I put it on bioconda, but it is gcc compiled. I have honestly no clue about how difficult/feasible it is to have it be intel compiled.
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bwa-mem2/meta.yaml

**Comment by rhpvorderman** [comment]
@Maarten-vd-Sande I did a comparison on a ryzen 5 3600 processor. The icpc binaries are faster even on a non-supported (AMD) CPU. It was about 4% faster. I also compiled locally using the AMD Optimizing C Compiler. The speedup was 5%. These differences are very minor. 

Extensive benchmarks can be found here https://github.com/biowdl/ngs-performance-choices#dna-alignment.

I unfortunately do not have a Intel desktop in reach to test. I can imagine the difference being larger on some intel xeon architectures. But I do not expect it to be more than 10%.

**Comment by Maarten-vd-Sande** [comment]
@rhpvorderman thanks for letting me know, I'll check out the comparison. I can live with up to 10% slower, but it's nice to know. ☺️

**Comment by keiranmraine** [comment]
I did analysis comparing icpc vs a couple of different gcc versions (as well as bwa vs bwa2), but it was very new intel vs very old AMD:

https://docs.google.com/spreadsheets/d/11RkIE_h5VsZJ3CeOjoyFm-cPysSreLnRv8zv4djnPMI/edit?usp=sharing

**Comment by rhpvorderman** [comment]
@keiranmraine Thanks a ton. That very new Intel with AVX512 is very interesting. I see it only requires 45,80% of the time of BWA using BWA-MEM2. The old opteron processors don't see these kind of benefits. On my zen2 architecture system (which would be comparable to last gen epyc systems, zen 3 has just come out) it required 53,98% of the BWA time using bwa-mem2. This is probably due to the fact that the used Ryzen 5 3600 processor supports only up to AVX2 and not AVX512. 
Interesting how these instruction sets for SIMD instructions provide real tangible benefits.

Also interesting to see how the ICPC compiled binary requires only 93,88% of the time of the GCC-compiled binary. Slightly more than a 6% improvement. For comparison the improvement using the AMD Optimized C Compiler (AOCC) on my AMD test system was about 5%. 

I think this provides good information for users. Do you really want those last 5-6% improvements in performance by compiling it yourself, or do you want to use [the biocontainer for bwa-mem2](https://quay.io/repository/biocontainers/bwa-mem2?tag=latest&tab=tags) which is compiled with GCC, but allows you to use the exact same binary as other people who make the same choice. In terms of reproducibility and auditability I prefer the latter, but YMMV.

**Comment by Maarten-vd-Sande** [comment]
Thanks both for the nice answers, I learned a lot! The spreadsheet is awesome. Plus the `performance choices` page is very informative, I did not know about `USE_JDK_DEFLATER=true`.

**Comment by rhpvorderman** [comment]
@Maarten-vd-Sande spread the word! We, bioinformaticians, are burning way too many CPU cycles unnecessarily. Much more patients can be helped, much more research can be done, if only we use the right tools at the correct settings. I am very grateful for bwa-mem2 tackling a huge chunk of the compute time needed for analysis.

**Comment by keiranmraine** [comment]
@rhpvorderman we do not use the biocontainers.  We use bwa-mem[2] embedded in optimised piped commands to minimise I/O, not in isolation.  Raw performance of BWA alone is only part of the problem if you then are shuttling the resulting data back and forth to disk.

Our container (with optimised bwa flow, [code](https://github.com/cancerit/PCAP-core), [container](https://quay.io/repository/wtsicgp/pcap-core)) is available for others to use and was the basis for [PCAWG](https://dcc.icgc.org/pcawg), [PanProstate](https://panprostate.org/) and some projects at [GDC](https://gdc.cancer.gov/).

**Comment by rhpvorderman** [comment]
@keiranmraine Great! Thanks for sharing. Biocontainers also have [multi package containers](https://github.com/BioContainers/multi-package-containers). We [do something similar](https://github.com/biowdl/tasks/blob/develop/bwa-mem2.wdl) by using such a container that contains the bwa-kit programmes and samtools to immediately output to a sorted bam file. 

If you are interested in eliminating disk I/O, might I suggest taking a look at the [isa-l project](https://github.com/intel/isa-l) it provides zlib-compatible compression and decompression at 3-6x the speed. This is already used by [xopen](https://github.com/marcelm/xopen) and by extension [cutadapt](https://github.com/marcelm/cutadapt) so at least the adapter trimming step doesn't lose too much time on compressing/decompressing.
